name: logd
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  csv: ^6.0.0
  supabase_flutter: ^2.8.0
  local_auth: ^2.3.0  # <--- CHECK DIT EN ZORG VOOR EXACT 2 SPATIES INSPRINGING!

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices.
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  # Vertelt Flutter dat er code gegenereerd moet worden (voor AppLocalizations)
  generate: true

  # The following line ensures that the Material Icons font is included
  uses-material-design: true

  # GECORRIGEERD: Met exact 2 spaties ingesprongen onder 'flutter:'
  assets:
    # GECORRIGEERD: Met exact 4 spaties ingesprongen onder 'flutter:'
    - assets/data/enemies.csv
    - assets/theme/
    - assets/story/nl/
    - assets/story/en/