class GuestManager {
  static bool isGuest = false;

  static Map<String, dynamic> guestProfile = {
    'id': 'guest_user_id',
    'username': 'Gast Reiziger',
    'level': 1,
    'hp': 20,
    'max_hp': 20,
    'gold_on_hand': 500,
    'gold_in_bank': 1000,
    'gems': 5,
    'turns': 30,
    'experience': 0,
    'alive': true,
    'is_married': false,
    'specialty': 'warrior',
    'race': 'Human',
    'dragon_points': 0,
    'bounty': 0,
    'reputation': 0,
    'dragon_kills': 0,
    'weapon_level': 0,
    'armor_level': 0,
    'mount_level': 0,
    'favor': 50,
    'romance_points': 0,
    'drinks_today': 0,
    'bard_buff': 'none',
    'dragon_breath_fights': 0,
    'permanent_bonus_atk': 0,
    'permanent_bonus_def': 0,
    'permanent_bonus_hp': 0,
    'permanent_bonus_turns': 0,
    'daily_deposited': 0,
    'prayed_this_turn': false,
    'confessed_this_turn': false,
    'lit_candle_this_turn': false,
    'gender': 'M',
    'has_ring': false,
    'potion_attack': 0,
    'potion_defense': 0,
    'elixirs_bought_today': 0,
    'last_reset': null,
  };

  static void resetGuestProfile() {
    isGuest = true;
    guestProfile = {
      'id': 'guest_user_id',
      'username': 'Gast Reiziger',
      'level': 1,
      'hp': 20,
      'max_hp': 20,
      'gold_on_hand': 500,
      'gold_in_bank': 1000,
      'gems': 5,
      'turns': 30,
      'experience': 0,
      'alive': true,
      'is_married': false,
      'specialty': 'warrior',
      'race': 'Human',
      'dragon_points': 0,
      'bounty': 0,
      'reputation': 0,
      'dragon_kills': 0,
      'weapon_level': 0,
      'armor_level': 0,
      'mount_level': 0,
      'favor': 50,
      'romance_points': 0,
      'drinks_today': 0,
      'bard_buff': 'none',
      'dragon_breath_fights': 0,
      'permanent_bonus_atk': 0,
      'permanent_bonus_def': 0,
      'permanent_bonus_hp': 0,
      'permanent_bonus_turns': 0,
      'daily_deposited': 0,
      'prayed_this_turn': false,
      'confessed_this_turn': false,
      'lit_candle_this_turn': false,
      'gender': 'M',
      'has_ring': false,
      'potion_attack': 0,
      'potion_defense': 0,
      'elixirs_bought_today': 0,
      'last_reset': null,
    };
  }
}
